declare const style: {
  readonly container: string
  readonly 'svg-wrapper': string
  readonly svg: string
  readonly 'asst-svg': string
  readonly dragging: string
  readonly 'button-list': string
  readonly 'right-bottom': string
  readonly 'right-top': string
  readonly disabled: string
  readonly gps: string
  readonly fit: string
  readonly root: string
  readonly selected: string
  readonly edited: string
  readonly text: string
  readonly outline: string
  readonly download: string
  readonly 'add-btn': string
  readonly 'hidden': string
  readonly 'expand-btn': string
  readonly 'collapse': string
  readonly content: string
  readonly trigger: string
  readonly menu: string
  readonly prev: string
  readonly next: string
}
export default style
